### ISSUE TITLE
Add support for Python 3.13

### ISSUE THREAD

**Issue by mcsken** [siisurit/check_done#30]
## Goals
> [!NOTE]  
> Now possible since moving away from coveralls, to use codecov which doesn't require any project dependencies to work.
 - [x] Upgrade to python 3.13. 
 
 Estimate: 0.5h

**Comment by roskakori** [comment]
Closing because we are not going to use coveralls, it's just too much of a hassle.

Support for Python 3.13 was already added with #31.

**Comment by mcsken** [comment]
Re-opening since we replaced coveralls with codecov in #35, which doesn't require any dependencies.
