### ISSUE TITLE
Fix supported Python version

### ISSUE THREAD

**Issue by roskakori** [siisurit/check_done#39]
## Background

Currently the pyproject.toml claims `3.10.` is supported, this should actually be `3.11.`:
```toml
[tool.poetry.dependencies]
python = ">=3.10, <3.14"
```
Also while at it, several dependencies can also be cleaned up in the `pyproject.toml`.

## Goals

- [x] Python versions `3.11.` `3.12.` `3.13.` are supported.
- [x] The following unused dependencies are removed:
    - [x] `pygments`
    - [x] `chardet`
    - [x] `rich`
    - [x] `gitpython`
    - [x] `pytest-mock`
    - [x] `pytest-order`
- [x] `requests` and `cryptography` are explicitly added to the dependencies.
- [x] [The old style dev dependency group is migrated to the new dev dependency style](https://python-poetry.org/docs/managing-dependencies#dependency-groups).
- [x] `requests-mock` is moved to dev dependencies.

Estimate: 1.5h

## Implementation notes

Dependencies should be removed with `poetry remove ...` and added with `poetry add ...`
You can put dependencies in a dev group with `poetry add ... --group dev`

**Comment by JMTyndall** [comment]
See #41
